### ISSUE TITLE
Sumário do Readme

### ISSUE THREAD

**Issue by Joaonorr** [dalton02/UFCHAT#1]
O projeto está ficando incrível!

Porém, seria bastante interessante adicionar duas coisas:

1. Um sumário para navegação do Readme;
2. Um guia dos pré-requisitos e como inicializar o projeto;

### Exemplo do sumário:

# Caminho Mínimo

- [Descrição](#descrição)
- [Modelagem](#modelagem)
  - [Variáveis](#variáveis)
  - [Modelo](#modelo)
- [Modelo de Programação Linear](#modelo-de-programação-linear)
- [Entrada](#entrada)
- [Exemplos](#exemplos)
  - [Entrada](#entrada-1)
  - [Saída](#saída)

**Comment by dalton02** [comment]
Adicionado meu querido! Mas acho que o guia de instalação ficará no futuro, teria que ser configurado uns 3 bancos de dados diferentes no sistema, não sei se seria prático isso :/

**Comment by Joaonorr** [comment]
Deixo aqui duas recomendações para fazer no futuro:

### Especificar os pré-requisitos.
Como o próprio título sugere, você pode informar que antes de levantar o serviço, a ambiente deve ter _n_ bancos e quais as portas em que cada serviço irá procurar, bem como deixar a porta modular também nas variáveis de ambiente de cada servidor.
Incluindo também os drives de conexão de cada ORM.

### Usando o docker compose.
Utilizando o docker e docker compose, você pode levantar quantos bancos quiser, impedindo com que o usuário se preocupe em configura-las.

Segue um template que você pode se basear:

```yml
services:
  db_service_1:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    container_name: postgresDB
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
      
  db_service_2:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=myuser2
      - POSTGRES_PASSWORD=mypassword2
    container_name: postgresDB2
    volumes:
      - ./pgdata:/var/lib/postgresql/data2
    ports:
      - '5433:5433'

```
